{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "311ee59d_db573513",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 3
      },
      "lineNbr": 0,
      "author": {
        "id": 1644679
      },
      "writtenOn": "2024-05-06T17:11:48Z",
      "side": 1,
      "message": "rerunning presubmits. The boot_test failure has no device logs to triage the issue.",
      "revId": "49a4a06264502fed3b8a61b67974d7e9f5abb342",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889"
    }
  ]
}